all:
	rm -f -- "$${HOME}/Library/Application Support/Sublime Text/Installed Packages/Strconv.sublime-package"
	zip -r9  "$${HOME}/Library/Application Support/Sublime Text/Installed Packages/Strconv.sublime-package" strconv.py strconv.sublime-commands
